In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('iris.data')

X = df.iloc[:, 0:4].values
y = df.iloc[:, 4:].values.reshape(-1,)

In [3]:
le = LabelEncoder()
y = le.fit_transform(y)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
from sklearn.svm import SVC
sv = SVC(kernel='linear').fit(X_train,y_train)

In [6]:
arr = np.array([[1.2, 2.3, 3.4, 4.4]])
pred = sv.predict(arr)

In [7]:
pred

array([2])

In [28]:
np.ravel(y_train)

array([1, 0, 0, 2, 0, 1, 2, 1, 0, 0, 1, 1, 2, 0, 0, 1, 1, 1, 2, 1, 1, 1,
       1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 1, 0, 0, 2, 2, 1, 2,
       0, 1, 2, 1, 2, 0, 2, 2, 0, 2, 2, 1, 2, 2, 0, 2, 0, 0, 1, 0, 2, 2,
       0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 1, 2, 1, 1, 1, 0, 2, 1, 1, 2, 0, 1,
       2, 0, 1, 0, 0, 2, 1, 0, 1, 1, 0, 0, 1, 2, 1, 1, 1, 0, 2, 1, 2, 2,
       0, 1, 0, 1, 2, 2, 0, 1, 2])

In [8]:
y_train

array([2, 1, 0, 0, 0, 0, 0, 2, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 0, 2, 0, 2,
       1, 1, 0, 2, 1, 2, 1, 0, 0, 1, 1, 1, 2, 0, 2, 1, 2, 2, 0, 0, 1, 1,
       2, 1, 2, 2, 2, 1, 0, 1, 1, 0, 2, 2, 1, 0, 2, 2, 2, 0, 0, 2, 0, 2,
       0, 2, 0, 0, 1, 1, 1, 0, 0, 0, 2, 2, 2, 1, 1, 1, 2, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 2, 1, 0, 1, 2, 2, 2, 1, 1, 0, 1, 2, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 2])